### ISSUE TITLE
Potential memory leak in SmoothGraphicsGeometry in version 0.0.17

### ISSUE THREAD

**Issue by aaclayton** [pixijs/graphics-smooth#12]
**Issue Details**
* Windows
* Chrome 96.0.4664.45
* `pixi/graphics-smooth`: 0.0.17
* PIXI canvas using WebGL2 renderer

--------------------------

Hello Ivan, thanks for creating this awesome extension. I am experiencing a memory leak using 0.0.17 which I believe traces back to `SmoothGraphicsGeometry`. I am currently testing with `SmoothGraphics` as a drop-in replacement using:
```js
PIXI.LegacyGraphics = PIXI.Graphics;
PIXI.Graphics = PIXI.smooth.SmoothGraphics;
```
When using `SmoothGraphics` I observe a steady increase in heap size as graphics objects are created. If I revert back to using the standard `PIXI.Graphics` the observed memory leak goes away.

I captured a short allocation timeline (including stack traces) using the Chrome dev tools profiler and have uploaded here: https://drive.google.com/file/d/1fRjh5yYY2sNlP89No7nvEXlgfM6-IyL2/view?usp=sharing

An example allocation from the timeline is depicted below:

![image](https://user-images.githubusercontent.com/2468703/144082638-06a33d53-c8be-462c-bb9a-bf6a40d87ada.png)

I don't know if there is additional information that I can provide to you that would help you reproduce or diagnose the issue - please let me know. Thanks!

**Comment by aaclayton** [comment]
UPDATE: This may not be due to SmoothGraphics afterall. I'm doing further tests with the base `PIXI.Graphics` and seeing a similar (but smaller) leak. I'm trying to diagnose the problem further - this may have been a false alarm. Will report back.

**Comment by aaclayton** [comment]
The issue was a problem on my side due to not explicitly calling `.destroy()` on graphics objects which were not batched and used their own geometry. Sorry for the false alarm, I did not realize that handling destruction of such graphics objects manually was required.

**Comment by ivanpopelyshev** [comment]
Yes, graphics-smooth geometry at the moment is bigger than usual Graphics, that will change when i finally add instancing here :)
