### ISSUE TITLE
Performance issues with lot of Graphics

### ISSUE THREAD

**Issue by Thel27** [pixijs/graphics-smooth#19]
Hi, first of all, a big thanks for this library.
I am currently trying to make a clone of [AutoCAD WebApp](https://web.autocad.com/acad/me). 
To do that, I have to use the Smooth Graphics plugins to get no scaling lines.
I'm pixi-viewport to move and zoom my view.
But I'm getting performance issue when I want to see my whole plan. (only this case because I used "cullable=true" in my graphics)
I got something like 20k Graphics on this plan, but I can get more.
Is there a way to increase Smooth Graphics performance, or maybe It's just my structure who's the problem ?

My actual app un-zoomed : 
![image](https://user-images.githubusercontent.com/33833440/180980184-64d10be0-16a3-4db3-858c-c471fb0f7e37.png)

Performance problem screen using chrome tools : 
![image](https://user-images.githubusercontent.com/33833440/180980386-05c381dd-27ad-4cdb-8552-6b8608657c97.png)

I'm using Containers to handle blocks (ex: a car or a chair) and doing a transform on it to place it : 
``` javascript
          const shapesBlock: Graphics[] = drawData(layer, shapesOfReferences, 0, true)
          let transform: PIXI.Transform = new PIXI.Transform()
          const mInsert = transform.localTransform.translate(0, 0)
          const yScale = d.Scale.Y || 1
          const xScale = d.Scale.X || 1
          let x = d.Position.X
          const y = maxY - d.Position.Y
          mInsert.scale(xScale, yScale)
          transform.localTransform.a = d.Matrix[0]
          transform.localTransform.b = -d.Matrix[4]
          transform.localTransform.c = -d.Matrix[1]
          transform.localTransform.d = d.Matrix[5]
          mInsert.translate(x, y)
          if (d.Normal && d.Normal.Z < 0) {
            mInsert.scale(-1, 1)
          }

          const blockContainer = new PIXI.Container()
          shapesBlock.forEach((shape) => {
            blockContainer.addChild(shape)
          })

          blockContainer.transform = transform
          
          shapesArray.push(blockContainer)
```

In my app, every shapes or blocks are handle in a specific container as a layer.
So It's like layer 1 : Container => shapes + containers(who contains shape)

Please let me know if you need additionnal info. I feel really stuck. I'm a student in internship and no one used Pixi before in my company...
Would love your help

**Comment by ivanpopelyshev** [comment]
Do you use dashed lines? if so, update  the plugin, we fixed it 2 weeks ago, @dev7355608 

0.0.30 at npm: 
https://www.npmjs.com/package/@pixi/graphics-smooth

**Comment by Thel27** [comment]
Hi @ivanpopelyshev, thanks for the fast answer.

> Do you use dashed lines? if so, update the plugin, we fixed it 2 weeks ago, @dev7355608

No I don't use smooth graphic dashed lines, I created my own function because I used PIXI.Graphics before.
Do you think it can be related ?

> Otherwise, it looks like its actual "10k bunnies problem" and you need special help with it.

Do you have any tips to help me with that ?

**Comment by dev7355608** [comment]
@ivanpopelyshev Would you say that uniforms updates having such a high impact on performance is unusual? I've noticed this too and always thought it's just a bottleneck of the current implementation, which seems to involve a lot of uniform updates.

**Comment by Thel27** [comment]
I found the solution to my problem. That was just the structure of my objects.
In my case, it is better to create only one "Graphics" object for a Block.

So this sentence : 
> It's better for batching to use many Graphics objects instead of a single Graphics with many shapes.

At [pixi js doc](https://pixijs.io/guides/basics/graphics.html) isn't always true. 

In my case, I will have interactivity for the whole block and not for the all shapes in the block.
Doing a Graphics by shapes is really to greedy.

So I think Smooth-Graphics doesn't perform as well as a default Graphics object but It's still not that bad. For the majority of cases, It will do the job.

Hope it helps someone ;)

**Comment by ivanpopelyshev** [comment]
Yeah, we didnt add batching and stuff yet ) Though it doesnt have bound textures so it should be fast.. the only exception is uniform binds which we have to swap to something else

**Comment by Thel27** [comment]
Hello, I just have a small question about the development of the "Graphic Smooth" plugin
Do you know when batching will be added ?
As I am making a clone of AutoCAD WebApp, I need a very good performance

**Comment by ivanpopelyshev** [comment]
Unfortunately, I dont have free time those months

Go to [pixijs repo](https://github.com/pixijs/pixijs/)  , add issue/discussion with bounty on it, someone will take it. Alternatively, ask guys in discord whether anyone wants to take it.
