### ISSUE TITLE
Extra pixel into miter line join.

### ISSUE THREAD

**Issue by Feu-Secret** [pixijs/graphics-smooth#2]
Result with SmoothGraphics
![image](https://user-images.githubusercontent.com/66535080/122563352-65d8e980-d044-11eb-8f10-c287898814cd.png)

Result with Graphics
![image](https://user-images.githubusercontent.com/66535080/122563545-9de02c80-d044-11eb-9956-d70b30e1ddb6.png)

**Comment by ivanpopelyshev** [comment]
Check `0.0.3` please , waiting when code-sandbox sees it

**Comment by Feu-Secret** [comment]
It's now working perfectly!

https://codesandbox.io/s/53uhp?file=/src/index.js
