### ISSUE TITLE
The graph is scaled and the actual graph width remains the same

### ISSUE THREAD

**Issue by pcbren1987** [pixijs/graphics-smooth#21]
The graph is scaled and the actual graph width remains the same

According to the middle mouse button scroll to zoom, use the PIXI. Graphics PIXI. Smooth. SmoothGraphics effect is not the same,
See links for examples
https://codepen.io/pcbren1987/pen/vYjZmgV

**Comment by ivanpopelyshev** [comment]
Please read about lineScaleMode: https://github.com/pixijs/graphics-smooth#linescalemode

**Comment by pcbren1987** [comment]
Thank you very much. Solved
