### ISSUE TITLE
Support Pixi 7

### ISSUE THREAD

**Issue by manico** [pixijs/graphics-smooth#29]
Is there a plan to support Pixi 7?

**Comment by miltoncandelero** [comment]
The line that is giving me problems right now for pixiv7 is https://github.com/pixijs/graphics-smooth/blob/7b5d86559c86c5534645fca45d01f125b49854b1/src/SmoothGraphics.ts#L711 
It seems renderer no longer stores/exposes the options used to create it so we can't read the antialias setting :(

**Comment by ivanpopelyshev** [comment]
move it to the setting and set to FALSE. This plugin is made to evade antialias webgl setting.
