### ISSUE TITLE
Missing side when drawing rounded rects

### ISSUE THREAD

**Issue by Feu-Secret** [pixijs/graphics-smooth#3]
Here access to the demo
https://codesandbox.io/s/smoothgraphics-rounded-rect-o3qfi?file=/src/index.js

![image](https://user-images.githubusercontent.com/66535080/123354948-f479c900-d564-11eb-9528-32ab73be6ef1.png)

**Comment by Feu-Secret** [comment]
Oh sorry... it's working perfectly with 0.5 !

**Comment by ivanpopelyshev** [comment]
Yep, it was fixed in `0.0.4`
