### ISSUE TITLE
`utils.premultiplyTint` deprecated

### ISSUE THREAD

**Issue by MuTsunTsai** [pixijs/graphics-smooth#39]
Since PIXI v7.2 a warning will show:

```
PixiJS Deprecation Warning: utils.premultiplyTint has moved to Color.toPremultiplied
Deprecated since v7.2.0
```

Which is caused by this part:

https://github.com/pixijs/graphics-smooth/blob/50064bc8e0e414ca804f023f56cfb26267d3e780/src/SmoothGraphicsGeometry.ts#L784

**Comment by dev7355608** [comment]
#40
