### ISSUE TITLE
Some edges of a polygon shape do not show

### ISSUE THREAD

**Issue by Feu-Secret** [pixijs/graphics-smooth#4]
It's a random behavior. That don't happen every times.

The lines are drawed with this parameter :
`static losLineStyle = {
    width: 10,
    color: 0xff0000,
    alignment: 0.5
  };`

The shape init :
`this.losGraphics.lineStyle(this.lineStyle).beginFill(0xFFFFFF, 1.0).drawPolygon(this.los).endFill();`

with `alignment 0.5` :
![image](https://user-images.githubusercontent.com/66535080/124730683-dec7b480-df11-11eb-93df-3e3c8807df7e.png)

with `alignment 0`:
![image](https://user-images.githubusercontent.com/66535080/124731040-28b09a80-df12-11eb-8863-a89ffc21788b.png)

**Comment by ivanpopelyshev** [comment]
The polygon was degenerate. Fixed here: https://github.com/pixijs/graphics-smooth/commit/7fd083f2dcf22261687c016b6768abe51970338b
